#!/usr/bin/env bash
# =========================================================
# Copyright 2020
#
#
# This is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with this file.  If not, see <http://www.gnu.org/licenses/>.
#
#
# =========================================================

PATH2SCRIPT=$(dirname "${BASH_SOURCE[0]}" )
## load shell functions
source $PATH2SCRIPT/metabinkit_shared.sh
PATH=$PATH:$PATH2SCRIPT/

set -eu -o pipefail


###############################################
# Default values
taxids_blacklist_files=
taxids_poslist_files=
outfmt="6 qseqid evalue pident qcovs saccver staxids ssciname sseqid"
threads=2
max_hsps=1
word_size=6
evalue=1
perc_identity=50
qcov_hsp_perc=98
gapopen=0
gapextend=2
reward=1
penalty=-1
max_target_seqs=100

taxdir=
infasta=
refdb=
outfile=


# using this directory as default
taxdir=$PATH2SCRIPT/../db/

###############################################
## Check if all tools/commands needed are present
COMMANDS_NEEDED="blastn taxonkit taxonkit_children.sh"
# 
# 
for cmd in $COMMANDS_NEEDED; do
    command -v $cmd  >/dev/null 2>&1 || { echo "ERROR: $cmd  does not seem to be installed.  Aborting." >&2; exit 1; }
done

check_blast_version 

###############################################
## 
function usage {
    cat <<EOF
metabinkit_blast -f fasta file -D reference_DB -o outfile [options]
 -f fasta_file 
 -D reference_db    - reference Blast indexed database
 -o outfile
 -O outformat       - output format (default: $outfmt)
 -T taxdir          - folder with NCBI's taxonomy database (default:$taxdir)
 -t threads         - maximum number of threads (default:$threads)
 -m max_hsps        - BLAST's max_hsps paramater (default:$max_hsps)
 -w word_size       - BLAST's word_size paramater (default:$word_size)
 -e evalue          - BLAST's evalue paramater (default:$evalue)
 -I perc_identity   - BLAST's perc_identity paramater (default:$perc_identity)
 -q qcov_hsp_perc   - BLASTS's qcov_hsp_perc paramater (default:$qcov_hsp_perc)
 -G gapopen         - BLASTS's gapopen paramater (default:$gapopen)
 -E gapextend       - BLASTS's gapextend paramater (default:$gapextend)
 -r reward
 -p penalty
 -M max_target_seqs
 -N taxids_blacklist_files - restrict search to taxids not present in the files provided (separated by comma). This options is incompatible with -P.
 -P taxids_positive_files - restrict search to taxids present in the files provided (separated by comma). This option is incompatible with -N.
 -v                       - print metabinkit version and exits
 -h                 - provides usage information

EOF
}


####################################################
#

OPTERR=0
while getopts "O:P:N:e:G:E:r:p:M:q:I:w:m:t:T:o:D:f:Vvdh"  Option; do
    case $Option in
	f ) infasta=$OPTARG;;
	d ) set -x;;
	D ) refdb=$OPTARG;;
	O ) outfmt="$OPTARG";;
	o ) outfile=$OPTARG;;
	T ) taxdir=$OPTARG;;
	t ) threads=$OPTARG;;
	m ) max_hsps=$OPTARG;;
	w ) word_size=$OPTARG;;
	I ) perc_identity=$OPTARG;;
	q ) qcov_hsp_perc=$OPTARG;;
	G ) gapopen=$OPTARG;;
	E ) gapextend=$OPTARG;;
	r ) reward=$OPTARG;;
	e ) evalue=$OPTARG;;
	p ) penalty=$OPTARG;;
	M ) max_target_seqs=$OPTARG;;
	N ) taxids_blacklist_files=$OPTARG;;
	P ) taxids_poslist_files=$OPTARG;;
	V ) set -x;;
	v ) print_metabinkit_version && exit 0;;
	h) usage; exit;;
	*) echo "ERROR: invalid option." ; usage; exit 1;;
    esac
done

print_metabinkit_version

## check mandatory arguments

if [ "$infasta-" == "-" ] || [ ! -e $infasta ]; then
    echo "ERROR: file (-f) not given or not found"
    exit 1
fi

if [ ! -e "$taxdir" ]; then
    echo "ERROR: taxdir folder $taxdir not found"
    exit 1
fi

#if [ ! -e "$refdb" ]; then
#    echo "ERROR: refdb $refdb not found"
#    exit 1
#fi

if [ "$outfile-" == "-" ]; then
    echo "ERROR: missing -o parameter"
    exit 1
fi

if [ "$taxids_blacklist_files-" != "-" ] &&  \
       [ "$taxids_poslist_files-" != "-" ] ; then
    echo "ERROR: option -N and -P cannot be used simultaneously"
    exit 1
fi
	 

####################################################################
## 
params="-max_hsps  $max_hsps  -task megablast  -perc_identity $perc_identity  -word_size $word_size -qcov_hsp_perc $qcov_hsp_perc -gapopen $gapopen -gapextend $gapextend -reward $reward -evalue $evalue -max_target_seqs $max_target_seqs -num_threads $threads -db $refdb"

if [ "$taxids_blacklist_files-" != "-" ]; then
    ## assumes that the number of files is relative small
    ## and the files may contain comments (#)
    cat $(echo $taxids_blacklist_files | tr "," " ") | sed "s/^#.*//"|grep -v "^$" > $outfile.taxidsblacklisted
    params="$params -negative_taxidlist $outfile.taxidsblacklisted"
fi

if [ "$taxids_poslist_files-" != "-" ]; then
    ## assumes that the number of files is relative small
    ## and the files may contain comments (#)
    cat $(echo $taxids_poslist_files | tr "," " ") | sed "s/^#.*//"|grep -v "^$" > $outfile.taxids
    params="$params -taxidlist $outfile.taxids"
fi



BLAST_CMD=blastn
## Subject Scientific Name(s) are separated by a ';'
$BLAST_CMD $params  -query $infasta  -out $outfile.tmp -outfmt "$outfmt"
echo "INFO: blast finished."

echo $outfmt| cut -f 2- -d\ |tr " " "\t" > $outfile.tmp2
cat $outfile.tmp >> $outfile.tmp2
mv $outfile.tmp2 $outfile
rm -f $outfile.tmp
exit 0
